### ISSUE TITLE
Overprint image assets for www have weird visual gaps

### ISSUE THREAD

**Issue by jessevondoom** [substationHQ/lodge#16]
The overprint branding was done in illustrator using the intersection pathfinder tool and separating the parts where each color overlapped. The side effect is that some of the edges where colors meet look broken, with some whitespace showing through. Need to rework these assets and reexport the SVGs.

(This isn't specific to Lodge or the www page — it's across all Substation branding on the Illustrator side.)

**Comment by jessevondoom** [comment]
In progress on this. Built the images a new way. Aligned their overprint angles because the different angles were driving me nuts. Making an alternate set now.

**Comment by jessevondoom** [comment]
The fix isn't 100% — the gaps are due to the vectors. But went with a more complex shape for higher resolution and it helps. Also did a little hand placing to minimize the high contrast areas.

**Comment by jessevondoom** [comment]
Update: made two fixes. The current state of the branch is a proper fix, with the earlier commit serving as a compromise. If all's well this should be closed soon.

**Comment by alanmoo** [comment]
I think we can close this, right?

**Comment by jessevondoom** [comment]
Yeah fixed!
