### ISSUE TITLE
Finish www buildout

### ISSUE THREAD

**Issue by jessevondoom** [substationHQ/lodge#17]
Copy and demo content are the big blockers here, but I'm making a placeholder issue for us and can build out more after talking to @alanmoo about his [flex branch](https://github.com/substation-me/lodge/tree/branded-demo-page).

**Comment by alanmoo** [comment]
Off the top of my head, I think I last decided that flexbox was the way to go for that page- I think I tried grid and ultimately realized it's not meant to work the way I wanted it to.

**Comment by jessevondoom** [comment]
I'm actually going to mark this as done since it's launched and we're just finishing up the demos, as mentioned in #28
